version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: sl-nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ../web:/var/www
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: sl-php
    volumes:
      - ../web:/var/www
    working_dir: /var/www
    depends_on:
      - mariadb
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis

  mariadb:
    image: mariadb:12.1.2
    container_name: sl-mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: baserool
      MYSQL_DB: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: sl-redis
    ports:
      - "6379:6379"

volumes:
  mariadb_data:
